name: rep-ci

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
    build:
      name: run rep tests
      runs-on: ubuntu-24.04

      steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install docutils pygments xmlschema
      - name: Run tests
        run: |
          make
