name: rep-ci

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
    build:
      name: run rep tests
      runs-on: ubuntu-20.04

      steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install docutils xmlschema
      - name: Run tests
        run: |
          make
